name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  staging:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
    - name: Build
      run: |
        npm install
        npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      env:
        AWS_S3_BUCKET: staging.genbukanmikayama.de
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'build'
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
    - name: Build
      run: |
        npm install
        npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*'
      env:
        AWS_S3_BUCKET: www.genbukanmikayama.de
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'build'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete --exclude '.git/*' --exclude '.github/*'
      env:
        AWS_S3_BUCKET: ninjutsu-bw.de
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'build'
    
